// Stateful browser regressions for equipment, saves, combat, quests and modal input.
// Run against a local static server. Configure PLAYWRIGHT_PATH, REALM_URL and
// REALM_EVIDENCE as in dialogue.browser.cjs. REALM_SCENARIOS optionally selects
// comma-separated groups; by default every group runs (about two minutes).
// Every scenario uses a fresh profile; all requests outside REALM_URL's origin
// are intercepted, including cloud saves. No user's existing save is touched.
// Resource grants, legacy saves and low-HP combat fixtures are explicit setup;
// normal menu, dialogue, attack, projectile and save callbacks perform the actions.
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const tag = 'systems-browser';
const url = process.env.REALM_URL || 'http://127.0.0.1:8097/glassrealm/';
const localOrigin = new URL(url).origin;
assert(['127.0.0.1', 'localhost', '[::1]'].includes(new URL(url).hostname), 'Use an isolated local game server');
const filter = process.env.REALM_SCENARIOS || 'equipment,death,bankcraft,crops,prayer,migration,combat,modal,prestige,quest,saga';
const out = path.resolve(process.env.REALM_EVIDENCE || '.visual-review/realm-systems/verification/durable');
fs.mkdirSync(out, { recursive: true });
const report={url,tag,started:new Date().toISOString(),scenarios:[],checks:[],errors:[],remote:[]};let browser,context,page,scenario;
async function state(){return page.evaluate(()=>{const g=__gr.G,s=g.save.snapshot();return{mode:__gr.mode,pos:__gr.pos,inventory:s.inventory,equipment:s.player.equipment,weapon:__gr.player.weapon(),bank:Object.fromEntries(Object.entries(s.bank).filter(([k,v])=>v>0)),hp:__gr.player.state.hp,maxHp:__gr.player.state.maxHp,prayer:__gr.player.state.prayer,maxPrayer:__gr.player.state.maxPrayer,xpMult:g.xpMult?g.xpMult():1,activePrayer:__gr.player.state.activePrayer,skills:s.skills,quests:s.quests,grave:s.grave||null,stats:s.stats,plots:__gr.world.plots.map(p=>({idx:p.idx,x:p.x,z:p.z,state:p.state,grow:p.grow,crop:p.crop})),render:{calls:__gr.drawCalls,triangles:__gr.triangles,lost:__gr.engine.renderer.getContext().isContextLost()}}});}
async function shot(name){await page.evaluate(()=>__gr.step(1));await page.waitForTimeout(120);const s=await state();assert(!s.render.lost&&s.render.calls>0,'healthy rendering');await page.screenshot({path:path.join(out,name+'.png')});fs.writeFileSync(path.join(out,name+'.json'),JSON.stringify(s,null,2));return s;}
async function key(k){await page.keyboard.press(k);await page.waitForTimeout(k==='Enter'?270:50);}
async function check(name,fn){try{await fn();report.checks.push({scenario,name,pass:true});console.log('PASS '+scenario+': '+name);}catch(e){report.checks.push({scenario,name,pass:false,message:e.message});console.log('FAIL '+scenario+': '+name+': '+e.message);await shot(scenario+'-failure-'+report.checks.length);}}
async function fresh(name){if(context)await context.close();scenario=name;report.scenarios.push(name);context=await browser.newContext({viewport:{width:900,height:780},serviceWorkers:'block'});await context.route('**/*',r=>{if(new URL(r.request().url()).origin===localOrigin)return r.continue();report.remote.push(r.request().url());return r.fulfill({status:200,contentType:'application/json',body:'null'});});page=await context.newPage();page.on('pageerror',e=>report.errors.push({scenario,message:e.message}));page.on('console',m=>{if(m.type()==='error')report.errors.push({scenario,message:m.text()});});await page.goto(url,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__gr&&__gr.mode==='picker');await page.evaluate(()=>__gr.pause());await key('Enter');assert.equal((await state()).mode,'world');await page.evaluate(()=>__gr.step(1));}
async function reload(){await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__gr);await page.evaluate(()=>__gr.pause());await page.waitForTimeout(150);}
async function pickerRow(text,sub){const rows=await page.locator('#pickerBody .row').allInnerTexts();const index=rows.findIndex(t=>t.includes(text)&&(!sub||t.includes(sub)));assert(index>=0,'picker row missing '+text+' '+sub+': '+rows.join('|'));for(let n=0;n<index;n++)await key('ArrowDown');await key('Enter');}
async function gearRow(text){await key('Tab');for(let i=0;i<14&&(await page.locator('#menuTabs .sel').innerText())!=='Gear';i++)await key('ArrowRight');const rows=await page.locator('#menuBody .row-title').allInnerTexts();const index=rows.findIndex(t=>t.includes(text));assert(index>=0,'gear row missing '+text+': '+rows);for(let n=0;n<index;n++)await key('ArrowDown');await key('Enter');await key('Escape');}
async function choice(text){const rows=await page.locator('#dlgChoices').locator(':scope > *').allInnerTexts();const index=rows.findIndex(t=>t.includes(text));assert(index>=0,'dialogue choice missing '+text+': '+rows.join('|'));for(let n=0;n<index;n++)await key('ArrowDown');await key('Enter');}
async function talk(npcKey){await page.evaluate(key=>{const n=__gr.G.entities.npcs.find(n=>n.def.key===key);if(!n)throw Error('NPC '+key+' missing');__gr.teleport(n.pos.x,n.pos.z+1.6);__gr.player.state.heading=Math.PI;__gr.G.input.clearHeld();__gr.step(4);if(__gr.G.currentTarget?.ref!==n)throw Error('NPC not target '+JSON.stringify(__gr.target()));},npcKey);await key('Enter');assert.equal((await state()).mode,'dialogue');}
async function run(){browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
if(!filter||filter.includes('equipment')){
 await fresh('equipment');
 await gearRow('Unarmed');await key('Tab');await shot('equipment-starter-unequipped');await check('starter sword remains owned and selectable after unequipping',async()=>assert((await page.locator('#menuBody').innerText()).includes('Bronze Sword'),'starter sword disappears permanently after choosing Unarmed'));await key('Escape');
 await page.evaluate(()=>{__gr.G.inventory.add('bronze_bar',3);__gr.G.openForge();});await pickerRow('Bronze Sword');await key('Escape');await gearRow('Bronze Sword');
 const bankBefore=await state();await page.evaluate(()=>__gr.G.openBank());await check('bank protects equipped copy and deposits any surplus',async()=>{if(bankBefore.inventory.bronze_sword>1){await pickerRow('Bronze Sword','tap to bank');const s=await state();assert.equal(s.inventory.bronze_sword,1);assert.equal(s.bank.bronze_sword,bankBefore.inventory.bronze_sword-1);assert.equal(s.equipment.weapon,'bronze_sword');}else assert(!(await page.locator('#pickerBody').innerText()).includes('Bronze Sword'));});await key('Escape');
 if(bankBefore.inventory.bronze_sword>1){await page.evaluate(()=>__gr.G.openBank());await pickerRow('Bronze Sword','tap to take');await check('withdrawing banked spare restores exact ownership without changing worn gear',async()=>{const s=await state();assert.equal(s.inventory.bronze_sword,bankBefore.inventory.bronze_sword);assert.equal(s.bank.bronze_sword||0,0);assert.equal(s.equipment.weapon,'bronze_sword');});await key('Escape');}
 const start=await state();await page.evaluate(()=>__gr.G.openShop());await shot('equipment-before-sale');while((await state()).inventory.bronze_sword){await pickerRow('Bronze Sword','tap to sell');if((await state()).inventory.bronze_sword){await key('Escape');await page.evaluate(()=>__gr.G.openShop());}}await shot('equipment-after-sale');
 await check('selling last equipped weapon reconciles ownership',async()=>{const s=await state();assert.equal(s.inventory.bronze_sword||0,0);assert.notEqual(s.equipment.weapon,'bronze_sword','sold weapon remains equipped');assert(s.inventory.gold>start.inventory.gold);});
 await reload();await shot('equipment-after-sale-reload');await check('sale reload does not resurrect free equipped weapon',async()=>{const s=await state();assert(!s.equipment.weapon||(s.inventory[s.equipment.weapon]||0)>0,'unowned equipped weapon after reload');});
}
if(!filter||filter.includes('death')){
 await fresh('death');await page.evaluate(()=>{__gr.teleport(90,30);__gr.G.inventory.add('wood',7);__gr.G.inventory.add('iron_ore',3);__gr.G.inventory.add('bronze_dagger',1);__gr.G.equipChoice({kind:'weapon',key:'bronze_dagger'});__gr.G.save.save();});const before=await state();await shot('death-before');await page.evaluate(()=>__gr.G.damagePlayer(10000));const dead=await shot('death-respawn');
 await check('standard death produces exact grave and clears carried items',async()=>{assert.deepStrictEqual(dead.grave.items,before.inventory);assert.equal(Object.values(dead.inventory).reduce((a,b)=>a+b,0),0);assert.equal(dead.stats.deaths,before.stats.deaths+1);assert.equal(dead.hp,dead.maxHp);});
 await check('standard death cannot use equipment left in grave',async()=>assert(Object.values(dead.equipment).every(v=>!v||(dead.inventory[v]||0)>0),'grave equipment still active on respawn'));
 await reload();const reloaded=await shot('death-reload');await check('saved grave remains reclaimable after reload',async()=>{assert(reloaded.grave,'saved grave lost on reload');assert.deepStrictEqual(reloaded.grave.items,before.inventory);});
 await page.evaluate(p=>{__gr.teleport(p.x,p.z);__gr.G.updateGrave(.016);},dead.grave);const claimed=await state();await check('reclaim after reload restores exact items once',async()=>{assert.deepStrictEqual(claimed.inventory,before.inventory);assert.equal(claimed.grave,null);await page.evaluate(()=>__gr.G.updateGrave(.016));assert.deepStrictEqual((await state()).inventory,before.inventory);});
 await reload();await check('reclaim survives another reload',async()=>{const s=await state();assert.deepStrictEqual(s.inventory,before.inventory);assert.equal(s.grave,null);});
}
if(!filter||filter.includes('bankcraft')){
 await fresh('bankcraft');await page.evaluate(()=>{__gr.G.inventory.add('wood',7);__gr.G.inventory.add('bronze_bar',2);});let before=await state();await page.evaluate(()=>__gr.G.openBank());await pickerRow('Driftwood','tap to bank');await check('bank deposit moves full stack exactly',async()=>{const s=await state();assert.equal(s.inventory.wood||0,0);assert.equal(s.bank.wood,7);});await key('Escape');await page.evaluate(()=>__gr.G.openBank());await pickerRow('Driftwood','tap to take');await check('bank withdraw restores full stack exactly',async()=>{const s=await state();assert.equal(s.inventory.wood,7);assert.equal(s.bank.wood||0,0);});await key('Escape');
 await page.evaluate(()=>__gr.G.openForge());const content=await page.evaluate(async()=>{const c=await import('./src/content.js');return c.FORGE.find(r=>r.out==='bronze_hatchet')});before=await state();await pickerRow('Bronze Hatchet');await check('forge consumes exact recipe and grants single output',async()=>{const s=await state();for(const[k,v]of Object.entries(content.cost))assert.equal(s.inventory[k]||0,(before.inventory[k]||0)-v);assert.equal(s.inventory.bronze_hatchet,(before.inventory.bronze_hatchet||0)+1);});await key('Escape');
 await page.evaluate(()=>{for(const k of Object.keys(__gr.G.inventory.serialize()))if(k!=='bronze_sword')__gr.G.inventory.remove(k,1e9);__gr.G.openForge();});before=await state();await pickerRow('Bronze Hatchet');await check('insufficient forge ingredients leave all resources and XP unchanged',async()=>{const s=await state();assert.deepStrictEqual(s.inventory,before.inventory);assert.deepStrictEqual(s.skills,before.skills);});await key('Escape');
 await page.evaluate(()=>__gr.G.openShop());before=await state();await pickerRow('Salve Flask');await check('insufficient purchase funds preserve items and gold',async()=>assert.deepStrictEqual((await state()).inventory,before.inventory));await key('Escape');
 await page.evaluate(()=>__gr.G.save.save());before=await state();await reload();await check('bank/craft inventory and XP persist',async()=>{const s=await state();assert.deepStrictEqual(s.inventory,before.inventory);assert.deepStrictEqual(s.bank,before.bank);assert.deepStrictEqual(s.skills,before.skills);});
}
if(filter.includes('saga')){
 await fresh('saga');await talk('vael');await choice('I will wake the shrine');await check('saga accepts through its authored dialogue',async()=>assert.equal((await state()).quests.q_saga_v1.status,'active'));
 const visit=await page.evaluate(async()=>{const {QUESTS}=await import('./src/content.js');const o=QUESTS.q_saga_v1.objectives.find(o=>o.type==='visit');__gr.teleport(o.x,o.z);__gr.step(2);return{x:o.x,z:o.z,r:o.r,pos:__gr.pos,progress:__gr.G.quests.progress('q_saga_v1','shrine'),saved:JSON.parse(localStorage.getItem('glassrealm.save.v1')).quests.q_saga_v1.progress.shrine};});await shot('saga-shrine');await check('scaled visit location is reachable and saves progress immediately',async()=>{assert(Math.hypot(visit.pos.x-visit.x,visit.pos.z-visit.z)<visit.r);assert.equal(visit.progress,1);assert.equal(visit.saved,1);});await reload();await talk('elder');await check('talk objective saves immediately on entering conversation',async()=>{const x=await page.evaluate(()=>({live:__gr.G.quests.progress('q_saga_v1','elder'),saved:JSON.parse(localStorage.getItem('glassrealm.save.v1')).quests.q_saga_v1.progress.elder}));assert.equal(x.live,1);assert.equal(x.saved,1);});await key('Escape');await page.evaluate(()=>{__gr.G.inventory.add('wood',6);__gr.G.perksOwned.add('scholar');});await talk('vael');const before=await state();await choice('Claim reward');await check('mixed-objective saga rewards respect active XP multiplier',async()=>{const s=await state();assert.equal(s.quests.q_saga_v1.status,'complete');assert.equal(s.inventory.wood||0,(before.inventory.wood||0)-6);assert.equal(s.inventory.gold,before.inventory.gold+120);assert.equal(s.skills.woodcutting,before.skills.woodcutting+Math.round(180*before.xpMult));assert.equal(s.skills.combat,before.skills.combat+Math.round(120*before.xpMult));});await check('completed have objectives stay completed after consuming turn-in items',async()=>assert(await page.evaluate(()=>__gr.G.quests.objectives('q_saga_v1').every(o=>o.done))));await reload();await check('talk visit and completed saga state persist together',async()=>{const s=await state();assert.equal(s.quests.q_saga_v1.status,'complete');assert.equal(s.quests.q_saga_v1.progress.shrine,1);assert.equal(s.quests.q_saga_v1.progress.elder,1);});
 const access=await page.evaluate(async()=>{const{QUESTS}=await import('./src/content.js');const rows=[];for(const[id,q]of Object.entries(QUESTS)){for(const o of q.objectives.filter(o=>o.type==='visit')){const r=o.r||9;let found=null;for(let d=0;d<=r&&!found;d+=Math.max(.6,r/8)){for(let a=0;a<Math.PI*2;a+=Math.PI/12){const x=o.x+Math.sin(a)*d,z=o.z+Math.cos(a)*d;if(__gr.world.canStand(x,z,.28)){found={x,z};break;}}}rows.push({quest:id,objective:o.id,x:o.x,z:o.z,r,legalStandingPoint:found});}}return rows;});fs.writeFileSync(path.join(out,'all-visit-objectives.json'),JSON.stringify(access,null,2));await check('all authored visit objectives contain reachable standing terrain',async()=>assert(access.every(r=>r.legalStandingPoint),JSON.stringify(access.filter(r=>!r.legalStandingPoint))));
}
if(filter.includes('modal')){
 await fresh('modal');await talk('elder');await choice('Chat');await page.keyboard.press('Enter');await page.keyboard.press('Enter');await check('rapid dialogue confirmations keep topic navigation open',async()=>{assert.equal((await state()).mode,'dialogue');assert((await page.locator('#dlgChoices > *').count())>2);});await key('Escape');
 await page.evaluate(()=>{__gr.G.inventory.add('gold',100);__gr.G.openShop();});const buy=await state();await page.keyboard.press('Enter');await page.keyboard.press('Enter');await check('rapid shop confirmations purchase twice and remain in picker',async()=>{const s=await state();assert.equal(s.mode,'picker');assert.equal(s.inventory.potion,buy.inventory.potion+2);});await key('Escape');
 const services=['openBank','openBusiness','openJobs','openFarm','openCook','openSmelt','openAlch','openSuperheat','openWardrobe','openFactions','openBrew','openFletch','openRune','openSawmill','openConstruct','openTavern','openCraft','openTravel','openSlayerShop'];await check('19 activity pickers open render and Escape returns to world',async()=>{for(const name of services){await page.evaluate(name=>__gr.G[name](),name);assert.equal((await state()).mode,'picker',name);assert((await page.locator('#pickerTitle').innerText()).length>0,name);await key('Escape');assert.equal((await state()).mode,'world',name);}});
 await page.evaluate(()=>{__gr.G.inventory.add('copper_ore',3);__gr.G.openSmelt();});const smelt=await state();await pickerRow('Bronze Bar');await check('smelting starts a world channel without premature consumption',async()=>{assert.equal((await state()).mode,'world');assert(await page.evaluate(()=>!!__gr.G.channel));assert.deepStrictEqual((await state()).inventory,smelt.inventory);});await key('ArrowUp');await page.evaluate(()=>__gr.step(1));await check('movement cancels craft without losing ingredients',async()=>{assert(!(await page.evaluate(()=>__gr.G.channel)));assert.deepStrictEqual((await state()).inventory,smelt.inventory);});
 await page.evaluate(()=>{__gr.G.input.clearHeld();__gr.step(70);__gr.G.openSmelt();});await pickerRow('Bronze Bar');await page.evaluate(()=>__gr.step(185));await check('completed smelting converts exact batch once',async()=>{const s=await state();assert.equal(s.inventory.copper_ore||0,0);assert.equal(s.inventory.bronze_bar,(smelt.inventory.bronze_bar||0)+3);assert(!(await page.evaluate(()=>__gr.G.channel)));});
 await page.evaluate(()=>{__gr.player.state.prayer=.1;__gr.G.togglePrayer('stoneskin');__gr.step(20);});await check('deterministic step drains and deactivates prayer',async()=>{const s=await state();assert.equal(s.prayer,0);assert.equal(s.activePrayer,null);});
 await page.evaluate(()=>{__gr.player.state.prayer=1;__gr.G.togglePrayer('stoneskin');__gr.openMenu();__gr.step(60);});await check('open menu pauses prayer and movement',async()=>assert.equal((await state()).prayer,1));await key('Escape');await page.evaluate(()=>__gr.step(10));await check('returning to world resumes prayer drain',async()=>assert((await state()).prayer<1));
 await page.evaluate(()=>{const d=__gr.world.stations.find(s=>s.kind==='door'&&s.building==='store');__gr.G.enterBuilding(d);__gr.player.state.prayer=.1;__gr.player.state.activePrayer='stoneskin';__gr.step(20);});await check('indoor active prayer also drains instead of freezing',async()=>{const s=await state();assert.equal(s.mode,'interior');assert.equal(s.prayer,0);assert.equal(s.activePrayer,null);});await page.evaluate(()=>__gr.G.openBank());await key('Escape');await check('indoor service Escape returns to interior',async()=>assert.equal((await state()).mode,'interior'));await page.evaluate(()=>__gr.G.exitInterior());await shot('modal-complete');
}
if(filter.includes('prestige')){
 await fresh('prestige');await page.evaluate(()=>{const g=__gr.G;g.gainXp('combat',50000);g.inventory.add('iron_sword',1);g.equipChoice({kind:'weapon',key:'iron_sword'});g.gainXp('prayer',50000);__gr.player.state.prayer=__gr.player.state.maxPrayer;g.togglePrayer('protmagic');});const equipped=await state();assert.equal(equipped.equipment.weapon,'iron_sword');assert.equal(equipped.activePrayer,'protmagic');await page.evaluate(()=>__gr.G.prestigeSkill('combat'));await check('combat prestige removes newly locked equipment while retaining owned item',async()=>{const s=await state();assert.equal(s.equipment.weapon,null);assert.equal(s.inventory.iron_sword,1);assert.equal(s.skills.combat,0);});await page.evaluate(()=>__gr.G.prestigeSkill('prayer'));await check('prayer prestige clears locked prayer and clamps maximum',async()=>{const s=await state();assert.equal(s.activePrayer,null);assert.equal(s.prayer,22);assert.equal(s.maxPrayer,22);assert.equal(s.skills.prayer,0);});await reload();await check('prestige restrictions and gear ownership persist',async()=>{const s=await state();assert.equal(s.equipment.weapon,null);assert.equal(s.inventory.iron_sword,1);assert.equal(s.prayer,22);assert.equal(s.skills.combat,0);assert.equal(s.skills.prayer,0);});await shot('prestige-complete');
}
if(filter.includes('combat')){
 await fresh('combat');
 const fixture=await page.evaluate(()=>{const g=__gr.G,p=__gr.player;__gr.teleport(25,45);g.skills.addXp('ranged',1000);g.inventory.add('oak_bow',1);g.equipChoice({kind:'weapon',key:'oak_bow'});p.state.combatStance='accurate';p.state.spec=100;p.state.attackCd=0;p.state.buffs={venom:{mult:1,t:90}};const pos=p.position;window._target=g.entities.spawnEnemy('boar',pos.x,pos.z-6);window._splash=g.entities.spawnEnemy('boar',pos.x+1.5,pos.z-6);_target.group.position.set(pos.x,pos.y,pos.z-6);_splash.group.position.set(pos.x+1.5,pos.y,pos.z-6);_target.hp=1000;_splash.hp=1;return{pos:__gr.pos,primary:{x:_target.pos.x,z:_target.pos.z,hp:_target.hp},splash:{x:_splash.pos.x,z:_splash.pos.z,hp:_splash.hp},label:'Synthetic 1 HP splash target and 1000 HP primary fixture, normal attack/projectile/entity callbacks; no grinding required.'};});fs.writeFileSync(path.join(out,'combat-fixture.json'),JSON.stringify(fixture,null,2));
 await page.evaluate(()=>__gr.G.attackEnemy(_target));
 await check('ranged shot applies neither damage DOT nor splash before impact',async()=>{const s=await page.evaluate(()=>({hp:_target.hp,dot:_target.dot,splash:_splash.hp,alive:_splash.alive}));assert.equal(s.hp,1000);assert(!s.dot);assert.equal(s.splash,1);assert(s.alive);});
 await page.evaluate(()=>{__gr.G.inventory.add('bronze_sword',1);__gr.G.equipChoice({kind:'weapon',key:'bronze_sword'});__gr.player.state.combatStance='defensive';});const pre=await state();await page.evaluate(()=>__gr.G.projectiles.update(1));
 await check('projectile impact applies damage poison and splash with captured ranged XP',async()=>{const x=await page.evaluate(()=>({hp:_target.hp,dot:_target.dot,splashAlive:_splash.alive,skill:_splash._lastSkill,xp:_splash.def.xp})),s=await state();assert(x.hp<1000);assert.equal(x.dot?.skill,'ranged');assert(!x.splashAlive);assert.equal(x.skill,'ranged');assert.equal(s.skills.ranged,pre.skills.ranged+Math.round(x.xp*pre.xpMult));assert.equal(s.skills.combat,pre.skills.combat);assert.equal(s.stats.kills,pre.stats.kills+1);});
 await page.evaluate(()=>{_target.hp=1;_target.dot.tick=.001;});const dotBefore=await state();await page.evaluate(()=>__gr.G.entities.update(.02,__gr.player));
 await check('poison kill retains original ranged attribution and clears DOT',async()=>{const x=await page.evaluate(()=>({alive:_target.alive,dot:_target.dot,xp:_target.def.xp})),s=await state();assert(!x.alive);assert(!x.dot);assert.equal(s.skills.ranged,dotBefore.skills.ranged+Math.round(x.xp*dotBefore.xpMult));assert.equal(s.skills.combat,dotBefore.skills.combat);});
 await page.evaluate(()=>{_target.dying=0;_target.respawn=0;__gr.teleport(_target.home.x+12,_target.home.z+12);__gr.G.entities.update(.02,__gr.player);});await check('respawn starts healthy with no stale poison or kill attribution',async()=>{const x=await page.evaluate(()=>({alive:_target.alive,hp:_target.hp,max:_target.maxHp,dot:_target.dot,skill:_target._lastSkill}));assert(x.alive);assert.equal(x.hp,x.max);assert(!x.dot);assert(!x.skill);});
 await page.evaluate(()=>{const g=__gr.G,p=__gr.player;p.state.attackCd=0;p.state.spec=0;p.state.buffs={};p.state.combatStance='accurate';p.state.hp=50;g.perksOwned.add('lifesteal');g.skills.addXp('combat',100000);window._leech=g.entities.spawnEnemy('boar',p.position.x,p.position.z-1.8);_leech.group.position.set(p.position.x,p.position.y,p.position.z-1.8);_leech.hp=1;g.attackEnemy(_leech);});await check('lifesteal heals from one actual HP rather than overkill damage',async()=>assert.equal((await state()).hp,51));
 await shot('combat-post-impact');
}
if(filter.includes('crops')){
 await fresh('crops');await page.evaluate(()=>{__gr.G.inventory.add('seeds',2);for(let i=0;i<__gr.world.plots.length;i++){const p=__gr.world.plots[i];for(let a=0;a<6.28;a+=.8){__gr.teleport(p.x+Math.sin(a)*1.7,p.z+Math.cos(a)*1.7);__gr.player.state.heading=a+Math.PI;__gr.step(1);if(__gr.G.currentTarget?.ref===p){window._plotIdx=i;return;}}}throw Error('no targetable plot')});const ix=await page.evaluate(()=>_plotIdx);const before=await state();await key('Enter');await shot('crops-planted');const planted=await state();await check('plant through normal target action consumes one seed',async()=>{assert.equal(planted.plots[ix].state,'growing');assert.equal(planted.inventory.seeds,before.inventory.seeds-1);});await reload();const growing=await state();await check('planted crop and remaining growth survive reload',async()=>{assert.equal(growing.plots[ix].state,'growing');assert.equal(growing.plots[ix].crop,'crop');assert(Math.abs(growing.plots[ix].grow-planted.plots[ix].grow)<3);});
 await page.evaluate(()=>{__gr.world.tick(60);__gr.G.save.save();});const grown=await state();await check('elapsed world time matures planted crop',async()=>assert.equal(grown.plots[ix].state,'grown'));await reload();const loaded=await shot('crops-grown-reload');await check('grown crop survives another reload',async()=>assert.equal(loaded.plots[ix].state,'grown'));
 await page.evaluate(ix=>{const p=__gr.world.plots[ix];for(let a=0;a<6.28;a+=.8){__gr.teleport(p.x+Math.sin(a)*1.7,p.z+Math.cos(a)*1.7);__gr.player.state.heading=a+Math.PI;__gr.step(1);if(__gr.G.currentTarget?.ref===p)return;}throw Error('plot no longer targetable')},ix);await key('Enter');const harvest=await state();await check('harvest grants a single yield and empties plot',async()=>{assert.equal(harvest.plots[ix].state,'empty');assert((harvest.inventory.crop||0)-(loaded.inventory.crop||0)>=2);assert((harvest.inventory.crop||0)-(loaded.inventory.crop||0)<=3);});await reload();await check('harvested plot and produce persist without duplication',async()=>{const s=await state();assert.equal(s.plots[ix].state,'empty');assert(harvest.inventory.crop>0);assert.equal(s.inventory.crop,harvest.inventory.crop);});
}
if(filter.includes('prayer')){
 await fresh('prayer');await check('locked prayer cannot activate',async()=>{await page.evaluate(()=>__gr.G.togglePrayer('keenedge'));assert.equal((await state()).activePrayer,null);});
 await key('Tab');for(let i=0;i<14&&(await page.locator('#menuTabs .sel').innerText())!=='Prayer';i++)await key('ArrowRight');await key('Enter');await key('Escape');await check('Prayer menu activates Stone Skin',async()=>assert.equal((await state()).activePrayer,'stoneskin'));
 const a=await state();await page.evaluate(()=>{__gr.player.state.prayer=.15;__gr.resume();});await page.waitForTimeout(1800);await page.evaluate(()=>__gr.pause());await check('real frame prayer drain reaches zero and deactivates',async()=>{const s=await state();assert.equal(s.prayer,0);assert.equal(s.activePrayer,null);});
 await page.evaluate(()=>__gr.G.togglePrayer('stoneskin'));await check('depleted prayer cannot reactivate',async()=>assert.equal((await state()).activePrayer,null));
 await page.evaluate(()=>{__gr.G.inventory.add('bones',2);const altar=__gr.world.stations.find(s=>s.kind==='altar');window._altar=altar;for(let a=0;a<6.28;a+=.7){__gr.teleport(altar.x+Math.sin(a)*2.5,altar.z+Math.cos(a)*2.5);__gr.player.state.heading=a+Math.PI;__gr.step(1);if(__gr.G.currentTarget?.ref===altar)return;}throw Error('altar no target')});const b=await state();await key('Enter');await check('altar consumes bones and restores leveled prayer maximum',async()=>{const s=await state();assert.equal(s.inventory.bones||0,0);assert.equal(s.skills.prayer,b.skills.prayer+Math.round(40*b.xpMult));assert.equal(s.prayer,s.maxPrayer);assert(s.maxPrayer>a.maxPrayer);});await shot('prayer-restored');await page.evaluate(()=>__gr.G.save.save());const c=await state();await reload();await check('prayer points and XP restore after reload',async()=>{const s=await state();assert.equal(s.prayer,c.prayer);assert.equal(s.skills.prayer,c.skills.prayer);});
}
if(filter.includes('migration')){
 await fresh('migration');const base=await page.evaluate(()=>__gr.G.save.snapshot());const old=JSON.parse(JSON.stringify(base));delete old.equipmentOwnership;old.inventory={potion:2,gold:40};old.player.equipment={weapon:'bronze_sword',armor:'leather_armor',shield:'wooden_shield',amulet:null,ring:null};old.stats.deaths=3;old.bank={};delete old.grave;
 await page.addInitScript(()=>{const f=sessionStorage.getItem('__fixture');if(f){localStorage.setItem('glassrealm.save.v1',f);sessionStorage.removeItem('__fixture');}}); async function loadFixture(s){await page.evaluate(s=>sessionStorage.setItem('__fixture',JSON.stringify(s)),s);await reload();}
 await loadFixture(old);const first=await state();await check('legacy worn starter gear materializes once including old experienced characters',async()=>{for(const k of ['bronze_sword','leather_armor','wooden_shield'])assert.equal(first.inventory[k],1);assert.equal(first.stats.deaths,3);});await page.evaluate(()=>__gr.G.save.save());await reload();await check('repeated reload never duplicates legacy kit',async()=>assert.deepStrictEqual((await state()).inventory,first.inventory));
 const bank=JSON.parse(JSON.stringify(old));bank.bank.bronze_sword=1;await loadFixture(bank);await check('legacy bank-held starter weapon is not duplicated',async()=>{const s=await state();assert.equal(s.inventory.bronze_sword||0,0);assert.equal(s.bank.bronze_sword,1);assert.equal(s.equipment.weapon,null);});
 const grave=JSON.parse(JSON.stringify(old));grave.grave={x:90,z:30,t:200,items:{bronze_sword:1}};await loadFixture(grave);await check('legacy grave-held starter weapon is not duplicated',async()=>{const s=await state();assert.equal(s.inventory.bronze_sword||0,0);assert.equal(s.equipment.weapon,null);assert.equal(s.grave.items.bronze_sword,1);});
 const marked=JSON.parse(JSON.stringify(old));marked.equipmentOwnership=1;await loadFixture(marked);await check('ownership marker prevents missing starter regeneration',async()=>{const s=await state();assert.equal(s.inventory.bronze_sword||0,0);assert.equal(s.equipment.weapon,null);});
 await page.evaluate(()=>{__gr.G.inventory.add('wood',9);__gr.G.bankItems.iron_ore=5;__gr.G.quests.accept('q_wood');__gr.G.save.save();window._portable=__gr.G.save.exportCode();});const portable=await state();await check('malformed portable import preserves existing save',async()=>{const r=await page.evaluate(()=>{const a=localStorage.getItem('glassrealm.save.v1');const ok=__gr.G.save.importCode(btoa(JSON.stringify({player:{},skills:'bad'})));return{ok,same:a===localStorage.getItem('glassrealm.save.v1')}});assert.equal(r.ok,false);assert(r.same);});await check('valid portable save imports and preserves progress',async()=>{assert(await page.evaluate(()=>__gr.G.save.importCode(_portable)));await reload();const s=await state();assert.deepStrictEqual(s.inventory,portable.inventory);assert.deepStrictEqual(s.bank,portable.bank);assert.deepStrictEqual(s.quests,portable.quests);});
}
if(!filter||filter.includes('quest')){
 await fresh('quest');await talk('elder');await choice('I will help');await choice('Understood');await check('elder accepts starter quest and tracks it',async()=>assert.equal((await state()).quests.q_wood.status,'active'));
 await reload();await check('active quest survives reload',async()=>assert.equal((await state()).quests.q_wood.status,'active'));
 for(let i=0;i<3;i++){const before=await state();await page.evaluate(()=>{__gr.G.input.clearHeld();for(const t of __gr.world.trees.filter(t=>t.alive&&Math.hypot(t.x,t.z)<85)){for(let a=0;a<6.28;a+=1.57){__gr.teleport(t.x+Math.sin(a)*2.7,t.z+Math.cos(a)*2.7);__gr.player.state.heading=a+Math.PI;__gr.step(1);if(__gr.G.currentTarget?.ref===t)return;}}throw Error('no target tree');});await key('Enter');assert(await page.evaluate(()=>!!__gr.G.channel),'channel failed');await page.evaluate(()=>__gr.step(280));await check('real gather '+(i+1)+' adds wood',async()=>assert((await state()).inventory.wood>(before.inventory.wood||0)));}
 await talk('elder');const ready=await state();await shot('quest-ready');await choice('Hand over 3');await choice('I will');await check('turn-in consumes three wood and grants exact reward',async()=>{const s=await state();assert.equal(s.quests.q_wood.status,'complete');assert.equal(s.quests.q_boar.status,'available');assert.equal(s.inventory.wood||0,(ready.inventory.wood||0)-3);assert.equal(s.inventory.gold,ready.inventory.gold+30);assert.equal(s.inventory.potion,ready.inventory.potion+1);assert.equal(s.skills.woodcutting,ready.skills.woodcutting+Math.round(120*ready.xpMult));});
 await reload();await talk('elder');const completed=await state();await choice('Chat');await shot('quest-gossip');await key('Enter');await choice('Ask something else');await key('Escape');await check('gossip and Escape return to world without duplicate reward',async()=>{const s=await state();assert.equal(s.mode,'world');assert.deepStrictEqual(s.inventory,completed.inventory);});
 await talk('ranger');await choice('Consider it done');await choice('Understood');await check('prerequisite unlock starts next quest',async()=>assert.equal((await state()).quests.q_boar.status,'active'));
 for(let i=0;i<2;i++){await page.evaluate(()=>{const e=__gr.G.entities.enemies.find(e=>e.enemyKey==='boar'&&e.alive);if(!e)throw Error('boar unavailable');window._boar=e;__gr.teleport(e.pos.x,e.pos.z+1.7);__gr.player.state.heading=Math.PI;__gr.step(1);if(__gr.G.currentTarget?.ref!==e)throw Error('boar not target');});await key('Enter');await page.evaluate(()=>__gr.step(600));await check('real combat kills boar '+(i+1),async()=>assert(await page.evaluate(()=>!_boar.alive)));}
 await talk('ranger');const b=await state();await shot('quest-boar-ready');await choice('Claim reward');await key('Enter');await check('kill quest turn-in grants reward once',async()=>{const s=await state();assert.equal(s.quests.q_boar.status,'complete');assert.equal(s.inventory.gold,b.inventory.gold+40);assert.equal(s.inventory.pelt,b.inventory.pelt+2);assert.equal(s.skills.combat,b.skills.combat+Math.round(160*b.xpMult));});await reload();await check('full quest chain completion persists',async()=>{const s=await state();assert.equal(s.quests.q_wood.status,'complete');assert.equal(s.quests.q_boar.status,'complete');});await shot('quest-chain-complete');
}
report.finished=new Date().toISOString();report.passed=report.checks.filter(c=>c.pass).length;report.failed=report.checks.filter(c=>!c.pass).length;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({passed:report.passed,failed:report.failed,errors:report.errors,out}));if(report.failed||report.errors.length)process.exitCode=1;}
run().catch(async e=>{report.fatal=e.stack;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.error(e);if(browser)await browser.close();process.exit(1)});




